apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-ssl
#   namespace: {{ .Values.namespace }}
spec:
  secretName: web-ssl-tls
  issuerRef:
    name: letsencrypt-production
    kind: Issuer
  commonName: {{ .Values.certificate.domain }}
  dnsNames:
  - {{ .Values.certificate.domain }} 
