apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-ssl
  namespace: {{ .Values.namespace }}
spec:
  secretName: web-api-ssl
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: {{ .Values.certificate.domain }}
  dnsNames:
  - {{ .Values.certificate.domain }}
