apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  # namespace: {{ .Values.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/zone: public
    external-dns.alpha.kubernetes.io/hostname: nasibaexample.online
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
#   tls:
#   - hosts:
    # - {{ .Values.ingress.hostname }}
    # - nasibaexample.online
    # secretName: web-ssl
  rules:
#   - host: {{ .Values.ingress.hostname }}
  - host: nasibaexample.online
    http:
      paths:
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /api/?(.*)
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80